Build Check Action: Show Errors/Warnings from Producer

diff --git a/.github/workflows/openknx-oam-check.yml b/.github/workflows/openknx-oam-check.yml
--- a/.github/workflows/openknx-oam-check.yml
+++ b/.github/workflows/openknx-oam-check.yml
@@ -66,7 +66,22 @@ jobs:
         run: cp -av OpenKNXproducer/tools/Linux/OpenKNXproducer /usr/local/bin/OpenKNXproducer
 
       - name: Create knxprod
-        run: OpenKNXproducer create --Debug -h include/knxprod.h src/${{inputs.KNXPROD_PREFIX}}${{ inputs.target != '' && format('-{0}', inputs.target) || '' }}
+        run: |
+          OpenKNXproducer create --Debug -h include/knxprod.h src/${{inputs.KNXPROD_PREFIX}}${{ inputs.target != '' && format('-{0}', inputs.target) || '' }} 2>&1 | tee producer.log
+          exit_code=${PIPESTATUS[0]}
+          if [ $exit_code -ne 0 ]; then
+            # Collect all outputs starting with "-->"
+            error_lines=$(grep -E '^\s*(-->|Unhandled exception\.)' producer.log | grep -Ev -- '--> Skipping creation of src/[^ \.]+\.knxprod due to check errors! <--' | tr '\n' ' // ')
+            if [ -n "$error_lines" ]; then
+              echo "::error:: $error_lines"
+            fi
+            exit $exit_code
+          fi
+
+          warn_lines=$(grep -E '^\s*-->\s*WARN' producer.log | tr '\n' ' // ')
+          if [ -n "$warn_lines" ]; then
+            echo "::warning:: $warn_lines"
+          fi
 
       - name: Install Python
         uses: actions/setup-python@v5
